# GitHub workflow action on workflow_dispatch (manual run):
#   In WordPress repository, update readme.txt and/or assets content.
#   Re-create {plugin-name}.{version}.zip to release assets.
#
# Define SVN_USERNAME, SVN_PASSWORD for wordpress.org credentials
# Organization or Repository : Settings -> Secrets and Variables -> Actions
#
# wordpress.org plugin slug is the repository name (lower case).
# Expects wordpress.org assets (screenshots, icons, banners) to be in /.wp-assets.
#
# See: https://github.com/10up/action-wordpress-plugin-asset-update/
#
# Version: 26.0822.1

name: On Dispatch, update readme
on:
  # Manually run from GitHub Actions UI
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  TAG_NAME:  ${{ github.ref_name }}
  WORKFLOW:  ${{ github.run_id }}

jobs:
  Update-Plugin:
    name: Update plugin readme and assets
    runs-on: ubuntu-latest

    steps:

    # Get plugin SLUG (lower-case) from REPO_NAME and VERSION (sans 'v') from TAG_NAME
    - name: Get Plugin Slug
      run: |
        echo "SLUG=${REPO_NAME,,}" >>${GITHUB_ENV}
        echo "VERSION=${TAG_NAME#v}" >>${GITHUB_ENV}

    # Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v7

    # Use CURL HEAD to check WordPress repository for plugin
    - name: Detect WordPress SVN
      id: detect_wp
      run: |
        STATUS=$(curl -o /dev/null -s -w "%{http_code}" -I https://plugins.svn.wordpress.org/${SLUG}/)
        echo "${SLUG} WP SVN STATUS=$STATUS"
        if [[ "$STATUS" =~ ^2 ]]; then
          echo "is_wp_plugin=true" >> $GITHUB_OUTPUT
        else
          echo "is_wp_plugin=false" >> $GITHUB_OUTPUT
        fi

    # -- Has WordPress Repository (is_wp_plugin == 'true') -- #

    # Update readme.txt & assets to trunk and stable-tag in WordPress SVN
    - name: Update Plugin SVN
      if: steps.detect_wp.outputs.is_wp_plugin == 'true'
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        ASSETS_DIR: .wp-assets
        IGNORE_OTHER_FILES: true
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

    # -- | -- #

    # Create zip archive from temp directory containing only files to include
    - name: Create Zip Archive
      run: |
        mkdir -p .${WORKFLOW}/${REPO_NAME}
        rsync -rc --exclude-from=.distignore --exclude='.${WORKFLOW}' ./ ./.${WORKFLOW}/${REPO_NAME}/ || \
        rsync -rc \
            --exclude='.*' \
            --exclude='/tests' \
            --exclude='/build' \
            --exclude='phpunit.xml*' \
            --exclude='composer.json' \
            --exclude='composer.lock' \
            --exclude='package.json' \
            --exclude='package-lock.json' \
        ./ ./.${WORKFLOW}/${REPO_NAME}/
        cd .${WORKFLOW}
        zip -r ../${REPO_NAME}.${VERSION}.zip-x ./${REPO_NAME}

    # Upload {plugin-name}.{version}.zip to github release
    - name: Upload Release Asset
      run: |
        gh release upload ${TAG_NAME} ${REPO_NAME}.${VERSION}-x.zip --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
